package solutions.year2018;

import java.util.List;

import com.github.aoclib.api.InputParser;
import com.github.aoclib.solver.DayX;

/**
 * <p>AUTOGENERATED BY DayGenerator.java</p>
 *
 * <p>https://github.com/vilhok/aoc-lib</p>
 *
 * <p>Edits in this file will not be overwritten.</p>
 *
 */
public class Year2018Day21 extends DayX {

	@Override
	public Object firstPart(InputParser input) {
		return NOT_SOLVED;
	}

	@Override
	public Object secondPart(InputParser input) {
		return NOT_SOLVED;
	}

	/*
	 * Optional: add tests for each part in the following methods
	 *
	 * These methods have blank implementations in superclass as well and can be deleted if you
	 * don't want to include tests.
	 *
	 * Add test as follows:
	 *
	 * new Test("sampleinput", expectedSolution);
	 *
	 * Collect the tests from the task web page.
	 */

	@Override
	protected void insertTestsPart1(List<Test> tests) {

	}

	@Override
	protected void insertTestsPart2(List<Test> tests) {

	}
}
